# Generated by Django 4.0.2 on 2022-02-21 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('feed', models.CharField(max_length=50)),
                ('datetime', models.TimeField(blank=True, default=datetime.datetime(2022, 2, 21, 20, 0, 28, 368365))),
            ],
        ),
    ]
